# the name used to display in the OS. Specifically desktop
# entry name
display_name: Linkwarden Mobile

# package name for debian/apt repository
# the name should be all lowercase with -+.
package_name: linkwarden-mobile

maintainer:
  name: Arran Ubels
  email: linkwardenmobile@arran4.com

# the size of binary in kilobyte
installed_size: 6604

# direct dependencies required by the application
# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# dependencies:
#   - libkeybinder-3.0-0 (>= 0.3.2)

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# build_dependencies_indep:
#   - texinfo

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# build_dependencies:
#   - kernel-headers-2.2.10 [!hurd-i386]
#   - gnumach-dev [hurd-i386]
#   - libluajit5.1-dev [i386 amd64 kfreebsd-i386 armel armhf powerpc mips]

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# recommended_dependencies:
#   - neofetch

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# suggested_dependencies:
#   - libkeybinder-3.0-0 (>= 0.3.2)

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# enhances:
#   - spotube

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# pre_dependencies:
#   - libc6

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks
# breaks:
#   - libspotify (<< 3.0.0)

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts
# conflicts:
#   - spotify

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides
# provides:
#   - libx11

# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-and-replacing-packages-replaces
# replaces:
#   - spotify

postinstall_scripts:
  - echo `Installed my awesome app`
postuninstall_scripts:
  - echo `Surprised Pickachu face`

# application icon path relative to project url
icon: assets/logo.png

keywords:
  - Link
  - Archiving
  - Bookmarking

# a name to categorize the app into a section of application
generic_name: Bookmark Management

# supported mime types that can be opened using this application
# supported_mime_type:
#   - audio/mpeg

metainfo: linux/packaging/linkwardenmobile.appdata.xml

# shown when right clicked the desktop entry icons
# actions:
#   - Gallery
#   - Create

# the categories the application belong to
# refer: https://specifications.freedesktop.org/menu-spec/latest/
categories:
  - Network
  - WebBrowser
  - Archiving

# let OS know if the application can be run on start_up. If it's false
# the application will deny to the OS if it was added as a start_up
# application
startup_notify: true
